name: 'CI/CD'
on:
  push:

jobs:
  ci:
    name: 'Continuous integration'
    runs-on: 'ubuntu-latest'
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'yarn'
          scope: '@kente-trial'
          registry-url: https://npm.pkg.github.com/
          always-auth: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Check format
        run: yarn run format:check

      - name: Check Linting
        run: yarn run lint:check

      - name: Run Unit testing
        run: yarn run test

      - name: Build artifacts
        run: yarn run build

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: npx semantic-release@23

      - name: Merge Semantic Release changes from release Branch in main Branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch
          git checkout release
          git pull
          git checkout main
          git merge release
          git push --force
